version: '3.7'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
  php:
    build: ./docker/php
    volumes: ['./app/:/var/www/app:cached']
  nginx:
    build: ./docker/nginx
    volumes: ['./app/:/var/www/app:cached']